on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Test Go
        run: go test -race ./...
  test-status:
    name: Test status
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set Check Status Success
        uses: Sibz/github-status-action@v1.1.6
        with:
          context: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: success